sonar.projectKey=aurimrv_api-test-generator-system
sonar.organization=aurimrv

# Use relative path from the sonar-project.properties file location
sonar.java.binaries=target/classes

# If you have multiple modules, list them separated by commas
# sonar.java.binaries=module1/target/classes,module2/target/classes

#sonar.sources=src/main/java
#sonar.tests=src/test/java

# Optional: specify test binaries
#sonar.java.test.binaries=target/test-classes

# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=api-test-generator-system
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8
