"""
JUnit 4 template for generating test code.
"""

import json
from typing import Dict, List, Any
from jinja2 import Template

from ..config.models import TestScenario, ProjectContext
from ..utils.logger import LoggerMixin


class JUnitTemplate(LoggerMixin):
    """
    Template generator for JUnit 4 test classes.
    
    Generates complete JUnit 4 test classes with Rest Assured integration
    for API integration testing.
    """
    
    def __init__(self):
        """Initialize the JUnit template."""
        self.logger.info("Initializing JUnit template")
        
        # Main test class template
        self.test_class_template = Template('''package {{ package_name }};

import org.junit.Before;
import org.junit.Test;
import org.junit.After;
import org.junit.BeforeClass;
import org.junit.AfterClass;
import org.junit.Ignore;
import static org.junit.Assert.*;
import static org.hamcrest.Matchers.*;

import io.restassured.RestAssured;
import io.restassured.response.Response;
import io.restassured.specification.RequestSpecification;
import static io.restassured.RestAssured.*;
import static io.restassured.matcher.RestAssuredMatchers.*;
import io.restassured.http.ContentType;

/**
 * Integration tests for {{ api_title }} API
 * Generated by API Test Generator System
 * 
 * Base URL: {{ base_url }}
 * API Version: {{ api_version }}
 */
public class {{ class_name }} {
    
    private static final String BASE_URL = "{{ base_url }}";
    private static final int DEFAULT_TIMEOUT = {{ default_timeout }};
    
    @BeforeClass
    public static void setUpClass() {
        RestAssured.baseURI = BASE_URL;
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
    }
    
    @AfterClass
    public static void tearDownClass() {
        RestAssured.reset();
    }
    
    @Before
    public void setUp() {
        // Setup before each test
    }
    
    @After
    public void tearDown() {
        // Cleanup after each test
    }
    
{% for test_method in test_methods %}
    {{ test_method }}
    
{% endfor %}
    
    // Helper methods
    
    private RequestSpecification givenDefaultRequest() {
        return given()
            .contentType(ContentType.JSON)
            .accept(ContentType.JSON);
    }
    
    private void validateResponseTime(Response response) {
        response.then().time(lessThan((long) DEFAULT_TIMEOUT * 1000));
    }
    
    private void validateJsonResponse(Response response) {
        response.then().contentType(ContentType.JSON);
    }
}''')
        
        # Individual test method template
        self.test_method_template = Template('''    /**
     * {{ description }}
     */
    @Test
    public void {{ method_name }}() {
        {{ test_body }}
    }''')
        
        # Ignored test method template
        self.ignored_test_template = Template('''    /**
     * {{ description }}
     * 
     * @ignore {{ ignore_reason }}
     */
    @Ignore("{{ ignore_reason }}")
    @Test
    public void {{ method_name }}() {
        {{ test_body }}
    }''')
    
    def generate_test_class(
        self,
        context: ProjectContext,
        scenarios: List[TestScenario],
        api_info: Dict[str, Any]
    ) -> str:
        """
        Generate a complete JUnit test class.
        
        Args:
            context: Project context
            scenarios: List of test scenarios
            api_info: API information
        
        Returns:
            Generated Java test class code
        """
        self.logger.info(f"Generating JUnit test class: {context.main_test_class_name}")
        
        # Generate individual test methods
        test_methods = []
        for scenario in scenarios:
            test_method = self._generate_test_method(scenario)
            test_methods.append(test_method)
        
        # Render the complete test class
        return self.test_class_template.render(
            package_name=context.package_name,
            class_name=context.main_test_class_name,
            api_title=api_info.get('title', 'API'),
            api_version=api_info.get('version', '1.0.0'),
            base_url=context.base_url,
            default_timeout=30,
            test_methods=test_methods
        )
    
    def _generate_test_method(self, scenario: TestScenario) -> str:
        """
        Generate a single test method.
        
        Args:
            scenario: Test scenario
        
        Returns:
            Generated test method code
        """
        test_body = self._generate_test_body(scenario)
        
        return self.test_method_template.render(
            method_name=scenario.name,
            description=scenario.description,
            test_body=test_body
        )
    
    def _generate_test_body(self, scenario: TestScenario) -> str:
        """
        Generate the body of a test method.
        
        Args:
            scenario: Test scenario
        
        Returns:
            Generated test body code
        """
        lines = []
        
        # Build the request
        request_parts = ["Response response = givenDefaultRequest()"]
        
        # Add path parameters
        path_params = self._extract_path_parameters(scenario)
        if path_params:
            for param_name, param_value in path_params.items():
                request_parts.append(f'            .pathParam("{param_name}", "{param_value}")')
        
        # Add query parameters
        query_params = self._extract_query_parameters(scenario)
        if query_params:
            for param_name, param_value in query_params.items():
                request_parts.append(f'            .queryParam("{param_name}", "{param_value}")')
        
        # Add request body if needed
        if scenario.method.upper() in ['POST', 'PUT', 'PATCH'] and scenario.test_data:
            body_json = self._format_json_body(scenario.test_data)
            #### Convert dictionary to compact JSON string (no newlines, no extra spaces) ####
            parsed = body_json.replace('\n', '')
            data = json.loads(parsed)
            json_str = json.dumps(data, separators=(", ", ": "))
            request_parts.append(f'            .body({json_str})')
        
        # Add the HTTP method and endpoint
        endpoint = self._resolve_endpoint_path(scenario.endpoint, path_params)
        request_parts.append(f'        .when()')
        request_parts.append(f'            .{scenario.method.lower()}("{endpoint}")')
        request_parts.append(f'        .then()')
        
        # Add status code assertion
        request_parts.append(f'            .statusCode({scenario.expected_status})')
        
        # Add response time validation
        request_parts.append('            .time(lessThan((long) DEFAULT_TIMEOUT * 1000))')
        
        # Add content type validation for successful responses
        if scenario.expected_status < 400:
            request_parts.append('            .contentType(ContentType.JSON)')
        
        # Add response body validations
        if scenario.expected_response_schema and not scenario.is_negative_test:
            validations = self._generate_response_validations(scenario.expected_response_schema)
            request_parts.extend(validations)
        
        # Complete the request
        request_parts.append('            .extract().response();')
        
        lines.append('\n'.join(request_parts))
        
        # Add additional assertions if needed
        if not scenario.is_negative_test:
            lines.append('')
            lines.append('        // Additional validations')
            lines.append('        validateResponseTime(response);')
            if scenario.expected_status < 400:
                lines.append('        validateJsonResponse(response);')
        
        return '\n        '.join(lines)
    
    def _extract_path_parameters(self, scenario: TestScenario) -> Dict[str, Any]:
        """Extract path parameters from scenario."""
        import re
        
        path_params = {}
        
        # Look for path parameters in the endpoint
        path_param_pattern = r'\{([^}]+)\}'
        matches = re.findall(path_param_pattern, scenario.endpoint)
        
        for param_name in matches:
            # Try to get value from scenario parameters
            if param_name in scenario.parameters:
                path_params[param_name] = scenario.parameters[param_name]
            else:
                # Generate a default value
                path_params[param_name] = self._generate_default_value(param_name)
        
        return path_params
    
    def _extract_query_parameters(self, scenario: TestScenario) -> Dict[str, Any]:
        """Extract query parameters from scenario."""
        import re
        
        query_params = {}
        
        # Get parameters that are not path parameters
        path_param_pattern = r'\{([^}]+)\}'
        path_param_names = re.findall(path_param_pattern, scenario.endpoint)
        
        for param_name, param_value in scenario.parameters.items():
            if param_name not in path_param_names:
                query_params[param_name] = param_value
        
        return query_params
    
    def _resolve_endpoint_path(self, endpoint: str, path_params: Dict[str, Any]) -> str:
        """Resolve endpoint path with path parameters."""
        resolved_path = endpoint
        
        for param_name, param_value in path_params.items():
            resolved_path = resolved_path.replace(f'{{{param_name}}}', f'{{{param_name}}}')
        
        return resolved_path
    
    def _generate_default_value(self, param_name: str) -> str:
        """Generate a default value for a parameter."""
        param_name_lower = param_name.lower()
        
        if 'id' in param_name_lower:
            return '1'
        elif 'name' in param_name_lower:
            return 'test'
        elif 'code' in param_name_lower:
            return 'TEST'
        elif 'email' in param_name_lower:
            return 'test@example.com'
        else:
            return 'sample'
    
    def _format_json_body(self, data: Dict[str, Any]) -> str:
        """Format data as JSON string for request body."""
        import json
        json_str = json.dumps(data, indent=2)
        # Escape quotes for Java string literal
        escaped_json = json_str.replace('"', '\\"')
        return f'"{escaped_json}"'
    
    def _generate_response_validations(self, response_schema: Dict[str, Any]) -> List[str]:
        """Generate response body validations."""
        validations = []
        
        # Basic validation - check if response is not empty
        validations.append('            .body("", not(empty()))')
        
        # Add specific field validations if schema is available
        if isinstance(response_schema, dict):
            # This is a simplified validation - a full implementation would
            # parse the JSON schema more thoroughly
            validations.append('            .body("size()", greaterThan(0))')
        
        return validations
    
    def generate_ignored_test(self, scenario: TestScenario, ignore_reason: str) -> str:
        """
        Generate an ignored test method.
        
        Args:
            scenario: Test scenario
            ignore_reason: Reason for ignoring the test
        
        Returns:
            Generated ignored test method code
        """
        test_body = self._generate_test_body(scenario)
        
        return self.ignored_test_template.render(
            method_name=scenario.name,
            description=scenario.description,
            ignore_reason=ignore_reason,
            test_body=test_body
        )
    
    def generate_helper_methods(self) -> str:
        """Generate additional helper methods."""
        return '''
    private void validateArrayResponse(Response response, int expectedSize) {
        response.then()
            .body("size()", equalTo(expectedSize));
    }
    
    private void validateObjectResponse(Response response, String... requiredFields) {
        for (String field : requiredFields) {
            response.then().body(field, notNullValue());
        }
    }
    
    private void validateErrorResponse(Response response, String expectedMessage) {
        response.then()
            .body("error", notNullValue())
            .body("message", containsString(expectedMessage));
    }'''

