package eu.fayder.restcountries.tests;

import org.junit.BeforeClass;
import org.junit.AfterClass;
import io.restassured.RestAssured;
import io.restassured.config.RestAssuredConfig;
import io.restassured.config.HttpClientConfig;
import io.restassured.specification.RequestSpecification;
import io.restassured.http.ContentType;
import static io.restassured.RestAssured.*;

/**
 * Base test class with common setup and utilities
 * Generated by API Test Generator System
 */
public abstract class BaseApiTest {
    
    @BeforeClass
    public static void globalSetUp() {
        // Configure RestAssured
        RestAssured.baseURI = TestConfig.BASE_URL;
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        
        // Configure timeouts
        RestAssured.config = RestAssuredConfig.config()
            .httpClient(HttpClientConfig.httpClientConfig()
                .setParam("http.connection.timeout", TestConfig.DEFAULT_TIMEOUT * 1000)
                .setParam("http.socket.timeout", TestConfig.DEFAULT_TIMEOUT * 1000));
    }
    
    @AfterClass
    public static void globalTearDown() {
        RestAssured.reset();
    }
    
    /**
     * Create a default request specification with common headers
     */
    protected RequestSpecification givenDefaultRequest() {
        return given()
            .contentType(ContentType.JSON)
            .accept(ContentType.JSON);
    }
    
    /**
     * Create a request specification for XML content
     */
    protected RequestSpecification givenXmlRequest() {
        return given()
            .contentType(ContentType.XML)
            .accept(ContentType.XML);
    }
    
    /**
     * Create a request specification with authentication
     */
    protected RequestSpecification givenAuthenticatedRequest() {
        return givenDefaultRequest()
            .header("Authorization", "Bearer " + getAuthToken());
    }
    
    /**
     * Get authentication token (override in subclasses if needed)
     */
    protected String getAuthToken() {
        return "test-token";
    }
}