"""
Deterministic post-processor that corrects Content-Type usage in
RestAssured-based JUnit 4 test classes generated by an LLM.

The fixer operates in two independent layers:

Layer 1 — Remove indevido (SAFE, no risk)
    When the OpenAPI spec says an endpoint has NO request body (ct=None),
    remove any .contentType() and .body() calls that the LLM added to the
    given() block for that endpoint.

Layer 2 — Fix wrong type (CONTROLLED risk)
    When the spec says an endpoint uses 'application/x-www-form-urlencoded'
    (i.e. it has 'in: formData' parameters in Swagger 2.x, or a
    requestBody with urlencoded content in OAS 3.x), and the LLM generated
    .contentType("application/json") + .body(JSON):
      - Replace the contentType value.
      - Convert .body("{...}") → individual .formParam() calls using the
        real formData parameter names from the spec.
      - If the LLM already used .formParam(), only fix the contentType.
      - If the JSON body contains fields NOT in the spec's formData params,
        the converter falls back conservatively and leaves the line unchanged.

Supports: Swagger 2.0, OpenAPI 3.0.x, OpenAPI 3.1.x

Usage (called from generator_agent.py after LLM generation):
    fixer = HttpContentTypeFixer(api_spec_dict)
    fixed_code = fixer.fix(java_code)
"""

import json
import re
from typing import Dict, List, Optional, Tuple


class HttpContentTypeFixer:
    """
    Post-processes LLM-generated RestAssured Java test code to ensure
    correct Content-Type usage based on the OpenAPI specification.
    """

    def __init__(self, api_spec: dict):
        """
        Args:
            api_spec: Parsed OpenAPI/Swagger specification dict.
        """
        self._spec = api_spec
        self._version = self._detect_version()
        self._endpoint_map = self._build_endpoint_map()

    # ------------------------------------------------------------------
    # Public interface
    # ------------------------------------------------------------------

    def fix(self, java_code: str) -> str:
        """
        Apply all content-type corrections to the generated Java code.

        Args:
            java_code: LLM-generated Java test class source code.

        Returns:
            Corrected Java source code.
        """
        if not java_code or not java_code.strip():
            return java_code

        lines = java_code.split('\n')
        result = self._process_lines(lines)
        return '\n'.join(result)

    # ------------------------------------------------------------------
    # Spec parsing
    # ------------------------------------------------------------------

    def _detect_version(self) -> str:
        """Return '2', '3.0', or '3.1' based on the spec."""
        if 'swagger' in self._spec:
            return '2'
        openapi_ver = self._spec.get('openapi', '3.0.0')
        if openapi_ver.startswith('3.1'):
            return '3.1'
        return '3.0'

    def _build_endpoint_map(self) -> Dict[str, Dict]:
        """
        Build a lookup map:
            (METHOD, path_pattern) -> {
                'ct': None | 'application/x-www-form-urlencoded' |
                      'multipart/form-data' | 'application/json' | ...,
                'form_params': [str, ...]   # names of formData params
            }
        Path patterns use the spec's original {param} notation.
        """
        result = {}
        global_consumes = self._spec.get('consumes', [])

        for path, methods in self._spec.get('paths', {}).items():
            for method, operation in methods.items():
                if not isinstance(operation, dict):
                    continue
                method_upper = method.upper()
                ct, form_params = self._infer_content_type(
                    operation, global_consumes
                )
                result[(method_upper, path)] = {
                    'ct': ct,
                    'form_params': form_params,
                }
        return result

    def _infer_content_type(
        self, operation: dict, global_consumes: List[str]
    ) -> Tuple[Optional[str], List[str]]:
        """
        Return (content_type, form_param_names) for one operation.

        content_type is None when the operation has no request body.
        """
        params = operation.get('parameters', [])

        if self._version == '2':
            # Swagger 2.0 — inspect 'in' field of each parameter
            form_params = [
                p['name'] for p in params if p.get('in') == 'formData'
            ]
            has_file = any(
                p.get('type') == 'file'
                for p in params if p.get('in') == 'formData'
            )
            has_body = any(p.get('in') == 'body' for p in params)

            if form_params:
                ct = 'multipart/form-data' if has_file \
                    else 'application/x-www-form-urlencoded'
                return ct, form_params
            if has_body:
                consumes = operation.get('consumes', global_consumes)
                ct = consumes[0] if consumes else 'application/json'
                return ct, []
            return None, []

        else:
            # OAS 3.0 / 3.1 — inspect requestBody.content
            rb = operation.get('requestBody', {})
            content = rb.get('content', {}) if rb else {}
            if not content:
                return None, []

            # Prefer application/json, then first key
            if 'application/json' in content:
                return 'application/json', []
            if 'application/x-www-form-urlencoded' in content:
                schema = content['application/x-www-form-urlencoded'].get(
                    'schema', {}
                )
                form_params = list(schema.get('properties', {}).keys())
                return 'application/x-www-form-urlencoded', form_params
            if 'multipart/form-data' in content:
                schema = content['multipart/form-data'].get('schema', {})
                form_params = list(schema.get('properties', {}).keys())
                return 'multipart/form-data', form_params

            first_ct = next(iter(content))
            return first_ct, []

    # ------------------------------------------------------------------
    # Java code processing
    # ------------------------------------------------------------------

    def _process_lines(self, lines: List[str]) -> List[str]:
        """
        Walk through lines identifying given()...when().METHOD(endpoint) blocks
        and apply corrections.

        Strategy:
        - Collect lines that form a single RestAssured call chain
          (a chain starts with given() and ends when .when() is followed
          by an HTTP method call).
        - For each complete chain, determine the endpoint + method from
          the .when().METHOD(url) portion.
        - Look up the spec's expected content-type.
        - Rewrite the given() portion accordingly.
        """
        # We work on a joined view to handle multi-line chains, then
        # split back. This is simpler and more robust than a pure
        # line-by-line state machine.
        code = '\n'.join(lines)
        fixed = self._fix_chains(code)
        return fixed.split('\n')

    # Regex to find a complete RestAssured call chain.
    # Captures:
    #   group 1: the given() prefix and all chained calls before .when()
    #   group 2: the HTTP method (get|post|put|delete|patch)
    #   group 3: the endpoint URL string (inside the method call parens)
    #   group 4: the rest of the chain after the URL (.then()...)
    _CHAIN_RE = re.compile(
        r'(given\s*\(\s*\)(?:\s*\.\s*\w+\s*\([^)]*\))*?)'  # given()...
        r'\s*\.\s*when\s*\(\s*\)'                            # .when()
        r'\s*\.\s*(get|post|put|delete|patch)\s*\('          # .METHOD(
        r'\s*["\']([^"\']+)[\"\']'                           # "endpoint"
        r'([^)]*)\)',                                         # rest of args)
        re.DOTALL | re.IGNORECASE,
    )

    # Alternative: when() may be on a separate line from the METHOD call
    # e.g.:  .when()\n    .post("/path")
    _CHAIN_RE2 = re.compile(
        r'(given\s*\(\s*\)(?:[\s\S]*?))'
        r'\.when\s*\(\s*\)'
        r'([\s\S]*?)'
        r'\.(get|post|put|delete|patch)\s*\(\s*["\']([^"\']+)["\']',
        re.DOTALL | re.IGNORECASE,
    )

    def _fix_chains(self, code: str) -> str:
        """
        Find every RestAssured given()...when().METHOD("url") chain and
        apply content-type corrections.
        """
        # Use a simple approach: find given() blocks and process them
        # We split the code into segments at each 'given(' boundary.
        result_parts = []
        last_end = 0

        # Find all given() positions
        for m in re.finditer(r'\bgiven\s*\(\s*\)', code):
            start = m.start()
            result_parts.append(code[last_end:start])

            # Extract the full chain starting from this given()
            chain_end, chain_text = self._extract_chain(code, start)
            if chain_end == -1:
                # Could not parse — leave unchanged
                result_parts.append(code[start:])
                last_end = len(code)
                break

            fixed_chain = self._fix_single_chain(chain_text)
            result_parts.append(fixed_chain)
            last_end = chain_end

        result_parts.append(code[last_end:])
        return ''.join(result_parts)

    def _extract_chain(self, code: str, start: int) -> Tuple[int, str]:
        """
        From the position of 'given()' extract the full RestAssured chain
        until the closing semicolon of the outermost call.

        Returns (end_position, chain_text) or (-1, '') if extraction fails.
        """
        # Find the semicolon that ends the statement, tracking parens/braces
        depth = 0
        i = start
        in_string = False
        string_char = None
        last_semi = -1

        while i < len(code):
            c = code[i]

            if in_string:
                if c == '\\':
                    i += 2
                    continue
                if c == string_char:
                    in_string = False
            else:
                if c in ('"', "'"):
                    in_string = True
                    string_char = c
                elif c == '(':
                    depth += 1
                elif c == ')':
                    depth -= 1
                elif c == ';' and depth == 0:
                    last_semi = i + 1
                    break

            i += 1

        if last_semi == -1:
            return -1, ''

        return last_semi, code[start:last_semi]

    def _fix_single_chain(self, chain: str) -> str:
        """
        Apply content-type corrections to a single given()...when().METHOD() chain.
        """
        # Extract HTTP method and endpoint from the chain
        method, endpoint = self._extract_method_and_endpoint(chain)
        if not method or not endpoint:
            return chain  # Cannot parse — leave unchanged

        # Look up spec
        spec_entry = self._match_spec_endpoint(method, endpoint)
        if spec_entry is None:
            return chain  # Endpoint not in spec — leave unchanged

        expected_ct = spec_entry['ct']
        form_params = spec_entry['form_params']

        # Detect what the LLM generated in the given() block
        has_ct, ct_value = self._detect_content_type(chain)
        has_form_param = bool(re.search(r'\.formParam\s*\(', chain))
        has_body = bool(re.search(r'\.body\s*\(', chain))

        # ----------------------------------------------------------------
        # Layer 1: Remove indevido — spec says no body
        # ----------------------------------------------------------------
        if expected_ct is None:
            if has_ct or has_body:
                chain = self._remove_content_type_and_body(chain)
            return chain

        # ----------------------------------------------------------------
        # Layer 2: Fix wrong type — spec says urlencoded
        # ----------------------------------------------------------------
        if expected_ct == 'application/x-www-form-urlencoded':
            if not has_ct and not has_form_param:
                # Missing entirely — add contentType + formParam
                # (conservative: only if we know the param names)
                if form_params:
                    chain = self._add_urlencoded(chain, form_params)
                return chain

            if has_ct and ct_value == 'application/json':
                if has_form_param and not has_body:
                    # CT wrong but formParam correct — just fix CT
                    chain = self._replace_content_type(
                        chain, 'application/x-www-form-urlencoded'
                    )
                elif has_body and not has_form_param:
                    # Both CT and body wrong — try to convert
                    chain = self._convert_json_body_to_form_params(
                        chain, form_params
                    )
                return chain

            if has_ct and ct_value != expected_ct:
                # e.g. multipart when urlencoded expected — fix CT only
                chain = self._replace_content_type(chain, expected_ct)
            return chain

        # ----------------------------------------------------------------
        # Layer 2b: Fix wrong type — spec says multipart/form-data
        # ----------------------------------------------------------------
        if expected_ct == 'multipart/form-data':
            if has_ct and ct_value == 'application/json':
                chain = self._replace_content_type(chain, expected_ct)
            return chain

        # ----------------------------------------------------------------
        # Layer 2c: Fix wrong type — spec says application/json
        # ----------------------------------------------------------------
        if expected_ct == 'application/json':
            if has_form_param and not has_body:
                # Has formParam but spec wants JSON — conservative: leave
                pass
            # If already has body(JSON) and correct CT: nothing to do
            return chain

        return chain

    # ------------------------------------------------------------------
    # Endpoint matching
    # ------------------------------------------------------------------

    def _extract_method_and_endpoint(
        self, chain: str
    ) -> Tuple[Optional[str], Optional[str]]:
        """
        Extract the HTTP method and URL from a given()...when().METHOD("url") chain.
        """
        m = re.search(
            r'\.when\s*\(\s*\)'
            r'[\s\S]*?\.'
            r'(get|post|put|delete|patch)\s*\(\s*["\']([^"\']+)["\']',
            chain, re.IGNORECASE,
        )
        if m:
            return m.group(1).upper(), m.group(2)

        # Also handle: .when()\n    .post("/path") with extra whitespace
        m2 = re.search(
            r'\.(get|post|put|delete|patch)\s*\(\s*["\']([^"\']+)["\']',
            chain, re.IGNORECASE,
        )
        if m2:
            return m2.group(1).upper(), m2.group(2)

        return None, None

    def _match_spec_endpoint(
        self, method: str, concrete_url: str
    ) -> Optional[Dict]:
        """
        Match a concrete URL (e.g. "/products/smartphone/features/camera")
        against the spec's path patterns (e.g. "/products/{productName}/features/{featureName}").

        Returns the spec entry dict or None if not matched.
        """
        # Normalise: strip query string
        url = concrete_url.split('?')[0].rstrip('/')

        # 1. Direct match (for URLs that happen to be literal spec paths)
        if (method, url) in self._endpoint_map:
            return self._endpoint_map[(method, url)]

        # 2. Pattern match
        for (spec_method, spec_path), entry in self._endpoint_map.items():
            if spec_method != method:
                continue
            if self._path_matches(url, spec_path):
                return entry

        return None

    @staticmethod
    def _path_matches(concrete: str, pattern: str) -> bool:
        """
        Return True if concrete path matches the spec pattern.
        E.g. "/products/smartphone" matches "/products/{productName}".
        """
        c_segs = [s for s in concrete.split('/') if s]
        p_segs = [s for s in pattern.split('/') if s]

        if len(c_segs) != len(p_segs):
            return False

        for c, p in zip(c_segs, p_segs):
            if p.startswith('{') and p.endswith('}'):
                continue  # path parameter — matches anything
            if c != p:
                return False
        return True

    # ------------------------------------------------------------------
    # Detection helpers
    # ------------------------------------------------------------------

    def _detect_content_type(self, chain: str) -> Tuple[bool, Optional[str]]:
        """
        Return (has_contentType, value) from the given() portion of a chain.
        Only looks inside given()...when().
        """
        given_part = self._extract_given_part(chain)
        m = re.search(
            r'\.contentType\s*\(\s*["\']([^"\']+)["\']\s*\)',
            given_part,
        )
        if m:
            return True, m.group(1)
        return False, None

    def _extract_given_part(self, chain: str) -> str:
        """Extract the portion of the chain between given() and .when()."""
        m = re.search(r'\.when\s*\(\s*\)', chain)
        if m:
            return chain[:m.start()]
        return chain

    # ------------------------------------------------------------------
    # Transformation helpers
    # ------------------------------------------------------------------

    def _remove_content_type_and_body(self, chain: str) -> str:
        """
        Remove .contentType("...") and .body("...") from the given() part.
        Leaves .formParam() calls untouched (they are explicit — keep them).
        Leaves .when(), .then(), and everything else untouched.
        """
        given_part = self._extract_given_part(chain)
        rest = chain[len(given_part):]

        # Remove .contentType("...")
        given_part = re.sub(
            r'\s*\.\s*contentType\s*\(\s*["\'][^"\']*["\']\s*\)',
            '',
            given_part,
        )

        # Remove .body("...") — handles single-line and multi-line body strings
        given_part = re.sub(
            r'\s*\.\s*body\s*\(\s*["\'][\s\S]*?["\']\s*\)',
            '',
            given_part,
        )

        return given_part + rest

    def _replace_content_type(self, chain: str, new_ct: str) -> str:
        """Replace the value inside .contentType("...") in the given() part."""
        given_part = self._extract_given_part(chain)
        rest = chain[len(given_part):]

        given_part = re.sub(
            r'(\.contentType\s*\(\s*)["\'][^"\']*["\']\s*(\))',
            rf'\g<1>"{new_ct}"\2',
            given_part,
        )
        return given_part + rest

    def _convert_json_body_to_form_params(
        self, chain: str, form_params: List[str]
    ) -> str:
        """
        Convert .contentType("application/json").body("{...}") to
        .contentType("application/x-www-form-urlencoded").formParam(...).

        Conservative: if the JSON fields don't match spec form params,
        or if parsing fails, returns the chain unchanged.
        """
        given_part = self._extract_given_part(chain)
        rest = chain[len(given_part):]

        # Extract the body string content
        body_m = re.search(
            r'\.body\s*\(\s*"([\s\S]*?)"\s*\)',
            given_part,
        )
        if not body_m:
            # body() call not found or too complex — leave unchanged
            return chain

        body_str = body_m.group(1)

        # Try to parse the JSON (handle escaped quotes)
        try:
            # Unescape Java string escapes
            unescaped = body_str.replace('\\"', '"').replace('\\\\', '\\')
            body_dict = json.loads(unescaped)
        except (json.JSONDecodeError, Exception):
            # Cannot parse — leave unchanged (conservative fallback)
            return chain

        if not isinstance(body_dict, dict):
            return chain

        # Check that all keys in the JSON are known spec form params
        # (or that form_params list is empty — meaning we accept any fields)
        if form_params:
            unknown = set(body_dict.keys()) - set(form_params)
            if unknown:
                # LLM used fields not in the spec — conservative: leave unchanged
                return chain

        # Build formParam calls
        # Detect indentation from existing chain
        indent_m = re.search(r'^(\s+)', given_part, re.MULTILINE)
        indent = indent_m.group(1) if indent_m else '            '

        form_param_calls = ''.join(
            f'\n{indent}.formParam("{k}", "{v}")'
            for k, v in body_dict.items()
        )

        # Remove .contentType("application/json") and .body("...")
        given_part = re.sub(
            r'\s*\.\s*contentType\s*\(\s*["\'][^"\']*["\']\s*\)',
            '',
            given_part,
        )
        given_part = re.sub(
            r'\s*\.\s*body\s*\(\s*"[\s\S]*?"\s*\)',
            '',
            given_part,
        )

        # Add correct contentType + formParam calls before .when()
        # Insert right before the end of given_part
        new_ct_call = f'\n{indent}.contentType("application/x-www-form-urlencoded")'
        given_part = given_part.rstrip() + new_ct_call + form_param_calls

        return given_part + rest

    def _add_urlencoded(self, chain: str, form_params: List[str]) -> str:
        """
        Add .contentType("application/x-www-form-urlencoded") to a chain
        that is missing it entirely. Does NOT add formParam values because
        we don't know what values to use — only adds the contentType.
        """
        given_part = self._extract_given_part(chain)
        rest = chain[len(given_part):]

        indent_m = re.search(r'^(\s+)', given_part, re.MULTILINE)
        indent = indent_m.group(1) if indent_m else '            '

        ct_call = f'\n{indent}.contentType("application/x-www-form-urlencoded")'
        given_part = given_part.rstrip() + ct_call

        return given_part + rest
