package org.javiermf.features.models.tests;

import org.junit.Before;
import org.junit.Test;
import org.junit.After;
import org.junit.BeforeClass;
import org.junit.AfterClass;
import org.junit.Ignore;
import static org.junit.Assert.*;
import static org.hamcrest.Matchers.*;

import io.restassured.RestAssured;
import io.restassured.response.Response;
import io.restassured.specification.RequestSpecification;
import static io.restassured.RestAssured.*;
import static io.restassured.matcher.RestAssuredMatchers.*;
import io.restassured.http.ContentType;

/**
 * Integration tests for API API
 * Generated by API Test Generator System
 * 
 * Base URL: http://localhost:8080
 * API Version: 1.0.0
 */
public class ApiIntegrationTest {
    
    private static final String BASE_URL = "http://localhost:8080";
    private static final int DEFAULT_TIMEOUT = 30;
    
    @BeforeClass
    public static void setUpClass() {
        RestAssured.baseURI = BASE_URL;
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
    }
    
    @AfterClass
    public static void tearDownClass() {
        RestAssured.reset();
    }
    
    @Before
    public void setUp() {
        // Setup before each test
    }
    
    @After
    public void tearDown() {
        // Cleanup after each test
    }
    

        /**
     * Test GET /products - success case with example data
     */
    @Test
    public void test_get__products_success() {
        Response response = givenDefaultRequest()
        .when()
            .get("/products")
        .then()
            .statusCode(200)
            .time(lessThan((long) DEFAULT_TIMEOUT * 1000))
            .contentType(ContentType.JSON)
            .extract().response();
        
                // Additional validations
                validateResponseTime(response);
                validateJsonResponse(response);
    }
    

        /**
     * Test POST /products/{productName} - success case with example data
     */
    @Test
    public void test_post__products_productName_success() {
        Response response = givenDefaultRequest()
            .pathParam("productName", "smartphone")
            .body("{  \"productName\": \"smartphone\"}")
        .when()
            .post("/products/{productName}")
        .then()
            .statusCode(201)
            .time(lessThan((long) DEFAULT_TIMEOUT * 1000))
            .contentType(ContentType.JSON)
            .extract().response();
        
                // Additional validations
                validateResponseTime(response);
                validateJsonResponse(response);
    }
    

        /**
     * Test GET /products/{productName} - success case with example data
     */
    @Test
    public void test_get__products_productName_success() {
        Response response = givenDefaultRequest()
            .pathParam("productName", "smartphone")
        .when()
            .get("/products/{productName}")
        .then()
            .statusCode(200)
            .time(lessThan((long) DEFAULT_TIMEOUT * 1000))
            .contentType(ContentType.JSON)
            .extract().response();
        
                // Additional validations
                validateResponseTime(response);
                validateJsonResponse(response);
    }
    

        /**
     * Test DELETE /products/{productName} - success case with example data
     */
    @Test
    public void test_delete__products_productName_success() {
        Response response = givenDefaultRequest()
            .pathParam("productName", "smartphone")
        .when()
            .delete("/products/{productName}")
        .then()
            .statusCode(204)
            .time(lessThan((long) DEFAULT_TIMEOUT * 1000))
            .contentType(ContentType.JSON)
            .extract().response();
        
                // Additional validations
                validateResponseTime(response);
                validateJsonResponse(response);
    }
    

        /**
     * Test GET /products/{productName}/features - success case with example data
     */
    @Test
    public void test_get__products_productName_features_success() {
        Response response = givenDefaultRequest()
            .pathParam("productName", "smartphone")
        .when()
            .get("/products/{productName}/features")
        .then()
            .statusCode(200)
            .time(lessThan((long) DEFAULT_TIMEOUT * 1000))
            .contentType(ContentType.JSON)
            .extract().response();
        
                // Additional validations
                validateResponseTime(response);
                validateJsonResponse(response);
    }
    

        /**
     * Test POST /products/{productName}/features/{featureName} - success case with example data
     */
    @Test
    public void test_post__products_productName_features_featureName_success() {
        Response response = givenDefaultRequest()
            .pathParam("productName", "smartphone")
            .pathParam("featureName", "camera")
            .queryParam("description", "High-resolution camera with optical zoom")
            .body("{  \"productName\": \"smartphone\",  \"featureName\": \"camera\",  \"description\": \"High-resolution camera with optical zoom\"}")
        .when()
            .post("/products/{productName}/features/{featureName}")
        .then()
            .statusCode(201)
            .time(lessThan((long) DEFAULT_TIMEOUT * 1000))
            .contentType(ContentType.JSON)
            .extract().response();
        
                // Additional validations
                validateResponseTime(response);
                validateJsonResponse(response);
    }
    

        /**
     * Test PUT /products/{productName}/features/{featureName} - success case with example data
     */
    @Test
    public void test_put__products_productName_features_featureName_success() {
        Response response = givenDefaultRequest()
            .pathParam("productName", "smartphone")
            .pathParam("featureName", "camera")
            .queryParam("description", "Ultra high-resolution camera with 10x optical zoom")
            .body("{  \"productName\": \"smartphone\",  \"featureName\": \"camera\",  \"description\": \"Ultra high-resolution camera with 10x optical zoom\"}")
        .when()
            .put("/products/{productName}/features/{featureName}")
        .then()
            .statusCode(200)
            .time(lessThan((long) DEFAULT_TIMEOUT * 1000))
            .contentType(ContentType.JSON)
            .extract().response();
        
                // Additional validations
                validateResponseTime(response);
                validateJsonResponse(response);
    }
    

        /**
     * Test DELETE /products/{productName}/features/{featureName} - success case with example data
     */
    @Test
    public void test_delete__products_productName_features_featureName_success() {
        Response response = givenDefaultRequest()
            .pathParam("productName", "smartphone")
            .pathParam("featureName", "camera")
        .when()
            .delete("/products/{productName}/features/{featureName}")
        .then()
            .statusCode(204)
            .time(lessThan((long) DEFAULT_TIMEOUT * 1000))
            .contentType(ContentType.JSON)
            .extract().response();
        
                // Additional validations
                validateResponseTime(response);
                validateJsonResponse(response);
    }
    

        /**
     * Test GET /products/{productName}/configurations - success case with example data
     */
    @Test
    public void test_get__products_productName_configurations_success() {
        Response response = givenDefaultRequest()
            .pathParam("productName", "smartphone")
        .when()
            .get("/products/{productName}/configurations")
        .then()
            .statusCode(200)
            .time(lessThan((long) DEFAULT_TIMEOUT * 1000))
            .contentType(ContentType.JSON)
            .extract().response();
        
                // Additional validations
                validateResponseTime(response);
                validateJsonResponse(response);
    }
    

        /**
     * Test POST /products/{productName}/configurations/{configurationName} - success case with example data
     */
    @Test
    public void test_post__products_productName_configurations_configurationName_success() {
        Response response = givenDefaultRequest()
            .pathParam("productName", "smartphone")
            .pathParam("configurationName", "premium")
            .body("{  \"productName\": \"smartphone\",  \"configurationName\": \"premium\"}")
        .when()
            .post("/products/{productName}/configurations/{configurationName}")
        .then()
            .statusCode(201)
            .time(lessThan((long) DEFAULT_TIMEOUT * 1000))
            .contentType(ContentType.JSON)
            .extract().response();
        
                // Additional validations
                validateResponseTime(response);
                validateJsonResponse(response);
    }
    

        /**
     * Test GET /products/{productName}/configurations/{configurationName} - success case with example data
     */
    @Test
    public void test_get__products_productName_configurations_configurationName_success() {
        Response response = givenDefaultRequest()
            .pathParam("productName", "smartphone")
            .pathParam("configurationName", "premium")
        .when()
            .get("/products/{productName}/configurations/{configurationName}")
        .then()
            .statusCode(200)
            .time(lessThan((long) DEFAULT_TIMEOUT * 1000))
            .contentType(ContentType.JSON)
            .extract().response();
        
                // Additional validations
                validateResponseTime(response);
                validateJsonResponse(response);
    }
    

        /**
     * Test DELETE /products/{productName}/configurations/{configurationName} - success case with example data
     */
    @Test
    public void test_delete__products_productName_configurations_configurationName_success() {
        Response response = givenDefaultRequest()
            .pathParam("productName", "smartphone")
            .pathParam("configurationName", "premium")
        .when()
            .delete("/products/{productName}/configurations/{configurationName}")
        .then()
            .statusCode(204)
            .time(lessThan((long) DEFAULT_TIMEOUT * 1000))
            .contentType(ContentType.JSON)
            .extract().response();
        
                // Additional validations
                validateResponseTime(response);
                validateJsonResponse(response);
    }
    

        /**
     * Test GET /products/{productName}/configurations/{configurationName}/features - success case with example data
     */
    @Test
    public void test_get__products_productName_configurations_configurationName_features_success() {
        Response response = givenDefaultRequest()
            .pathParam("productName", "smartphone")
            .pathParam("configurationName", "premium")
        .when()
            .get("/products/{productName}/configurations/{configurationName}/features")
        .then()
            .statusCode(200)
            .time(lessThan((long) DEFAULT_TIMEOUT * 1000))
            .contentType(ContentType.JSON)
            .extract().response();
        
                // Additional validations
                validateResponseTime(response);
                validateJsonResponse(response);
    }
    

        /**
     * Test POST /products/{productName}/configurations/{configurationName}/features/{featureName} - success case with example data
     */
    @Test
    public void test_post__products_productName_configurations_configurationName_features_featureName_success() {
        Response response = givenDefaultRequest()
            .pathParam("productName", "smartphone")
            .pathParam("configurationName", "premium")
            .pathParam("featureName", "camera")
            .body("{  \"productName\": \"smartphone\",  \"configurationName\": \"premium\",  \"featureName\": \"camera\"}")
        .when()
            .post("/products/{productName}/configurations/{configurationName}/features/{featureName}")
        .then()
            .statusCode(201)
            .time(lessThan((long) DEFAULT_TIMEOUT * 1000))
            .contentType(ContentType.JSON)
            .extract().response();
        
                // Additional validations
                validateResponseTime(response);
                validateJsonResponse(response);
    }
    

        /**
     * Test DELETE /products/{productName}/configurations/{configurationName}/features/{featureName} - success case with example data
     */
    @Test
    public void test_delete__products_productName_configurations_configurationName_features_featureName_success() {
        Response response = givenDefaultRequest()
            .pathParam("productName", "smartphone")
            .pathParam("configurationName", "premium")
            .pathParam("featureName", "camera")
        .when()
            .delete("/products/{productName}/configurations/{configurationName}/features/{featureName}")
        .then()
            .statusCode(204)
            .time(lessThan((long) DEFAULT_TIMEOUT * 1000))
            .contentType(ContentType.JSON)
            .extract().response();
        
                // Additional validations
                validateResponseTime(response);
                validateJsonResponse(response);
    }
    

        /**
     * Test POST /products/{productName}/constraints/requires - success case with example data
     */
    @Test
    public void test_post__products_productName_constraints_requires_success() {
        Response response = givenDefaultRequest()
            .pathParam("productName", "smartphone")
            .queryParam("sourceFeature", "advanced-camera")
            .queryParam("requiredFeature", "high-resolution-display")
            .body("{  \"productName\": \"smartphone\",  \"sourceFeature\": \"advanced-camera\",  \"requiredFeature\": \"high-resolution-display\"}")
        .when()
            .post("/products/{productName}/constraints/requires")
        .then()
            .statusCode(201)
            .time(lessThan((long) DEFAULT_TIMEOUT * 1000))
            .contentType(ContentType.JSON)
            .extract().response();
        
                // Additional validations
                validateResponseTime(response);
                validateJsonResponse(response);
    }
    

        /**
     * Test POST /products/{productName}/constraints/excludes - success case with example data
     */
    @Test
    public void test_post__products_productName_constraints_excludes_success() {
        Response response = givenDefaultRequest()
            .pathParam("productName", "smartphone")
            .queryParam("sourceFeature", "budget-processor")
            .queryParam("excludedFeature", "gaming-gpu")
            .body("{  \"productName\": \"smartphone\",  \"sourceFeature\": \"budget-processor\",  \"excludedFeature\": \"gaming-gpu\"}")
        .when()
            .post("/products/{productName}/constraints/excludes")
        .then()
            .statusCode(201)
            .time(lessThan((long) DEFAULT_TIMEOUT * 1000))
            .contentType(ContentType.JSON)
            .extract().response();
        
                // Additional validations
                validateResponseTime(response);
                validateJsonResponse(response);
    }
    

        /**
     * Test DELETE /products/{productName}/constraints/{constraintId} - success case with example data
     */
    @Test
    public void test_delete__products_productName_constraints_constraintId_success() {
        Response response = givenDefaultRequest()
            .pathParam("productName", "smartphone")
            .pathParam("constraintId", "123")
        .when()
            .delete("/products/{productName}/constraints/{constraintId}")
        .then()
            .statusCode(204)
            .time(lessThan((long) DEFAULT_TIMEOUT * 1000))
            .contentType(ContentType.JSON)
            .extract().response();
        
                // Additional validations
                validateResponseTime(response);
                validateJsonResponse(response);
    }
    

        /**
     * Test GET / (found in source code)
     */
    @Test
    public void test_get___source_code() {
        Response response = givenDefaultRequest()
        .when()
            .get("/")
        .then()
            .statusCode(200)
            .time(lessThan((long) DEFAULT_TIMEOUT * 1000))
            .contentType(ContentType.JSON)
            .extract().response();
        
                // Additional validations
                validateResponseTime(response);
                validateJsonResponse(response);
    }
    

        /**
     * Test GET /{configurationName} (found in source code)
     */
    @Test
    public void test_get__configurationName_source_code() {
        Response response = givenDefaultRequest()
            .pathParam("configurationName", "test")
        .when()
            .get("/{configurationName}")
        .then()
            .statusCode(200)
            .time(lessThan((long) DEFAULT_TIMEOUT * 1000))
            .contentType(ContentType.JSON)
            .extract().response();
        
                // Additional validations
                validateResponseTime(response);
                validateJsonResponse(response);
    }
    

        /**
     * Test POST /{configurationName} (found in source code)
     */
    @Test
    public void test_post__configurationName_source_code() {
        Response response = givenDefaultRequest()
            .pathParam("configurationName", "test")
        .when()
            .post("/{configurationName}")
        .then()
            .statusCode(200)
            .time(lessThan((long) DEFAULT_TIMEOUT * 1000))
            .contentType(ContentType.JSON)
            .extract().response();
        
                // Additional validations
                validateResponseTime(response);
                validateJsonResponse(response);
    }
    

        /**
     * Test DELETE /{configurationName} (found in source code)
     */
    @Test
    public void test_delete__configurationName_source_code() {
        Response response = givenDefaultRequest()
            .pathParam("configurationName", "test")
        .when()
            .delete("/{configurationName}")
        .then()
            .statusCode(200)
            .time(lessThan((long) DEFAULT_TIMEOUT * 1000))
            .contentType(ContentType.JSON)
            .extract().response();
        
                // Additional validations
                validateResponseTime(response);
                validateJsonResponse(response);
    }
    

        /**
     * Test POST /{featureName} (found in source code)
     */
    @Test
    public void test_post__featureName_source_code() {
        Response response = givenDefaultRequest()
            .pathParam("featureName", "test")
        .when()
            .post("/{featureName}")
        .then()
            .statusCode(200)
            .time(lessThan((long) DEFAULT_TIMEOUT * 1000))
            .contentType(ContentType.JSON)
            .extract().response();
        
                // Additional validations
                validateResponseTime(response);
                validateJsonResponse(response);
    }
    

        /**
     * Test DELETE /{featureName} (found in source code)
     */
    @Test
    public void test_delete__featureName_source_code() {
        Response response = givenDefaultRequest()
            .pathParam("featureName", "test")
        .when()
            .delete("/{featureName}")
        .then()
            .statusCode(200)
            .time(lessThan((long) DEFAULT_TIMEOUT * 1000))
            .contentType(ContentType.JSON)
            .extract().response();
        
                // Additional validations
                validateResponseTime(response);
                validateJsonResponse(response);
    }
    

        /**
     * Test PUT /{featureName} (found in source code)
     */
    @Test
    public void test_put__featureName_source_code() {
        Response response = givenDefaultRequest()
            .pathParam("featureName", "test")
        .when()
            .put("/{featureName}")
        .then()
            .statusCode(200)
            .time(lessThan((long) DEFAULT_TIMEOUT * 1000))
            .contentType(ContentType.JSON)
            .extract().response();
        
                // Additional validations
                validateResponseTime(response);
                validateJsonResponse(response);
    }
    

        /**
     * Test POST /requires (found in source code)
     */
    @Test
    public void test_post__requires_source_code() {
        Response response = givenDefaultRequest()
        .when()
            .post("/requires")
        .then()
            .statusCode(200)
            .time(lessThan((long) DEFAULT_TIMEOUT * 1000))
            .contentType(ContentType.JSON)
            .extract().response();
        
                // Additional validations
                validateResponseTime(response);
                validateJsonResponse(response);
    }
    

        /**
     * Test POST /excludes (found in source code)
     */
    @Test
    public void test_post__excludes_source_code() {
        Response response = givenDefaultRequest()
        .when()
            .post("/excludes")
        .then()
            .statusCode(200)
            .time(lessThan((long) DEFAULT_TIMEOUT * 1000))
            .contentType(ContentType.JSON)
            .extract().response();
        
                // Additional validations
                validateResponseTime(response);
                validateJsonResponse(response);
    }
    

        /**
     * Test DELETE /{constraintId} (found in source code)
     */
    @Test
    public void test_delete__constraintId_source_code() {
        Response response = givenDefaultRequest()
            .pathParam("constraintId", "1")
        .when()
            .delete("/{constraintId}")
        .then()
            .statusCode(200)
            .time(lessThan((long) DEFAULT_TIMEOUT * 1000))
            .contentType(ContentType.JSON)
            .extract().response();
        
                // Additional validations
                validateResponseTime(response);
                validateJsonResponse(response);
    }
    

    
    // Helper methods
    
    private RequestSpecification givenDefaultRequest() {
        return given()
            .contentType(ContentType.JSON)
            .accept(ContentType.JSON);
    }
    
    private void validateResponseTime(Response response) {
        //response.then().time(lessThan((long) DEFAULT_TIMEOUT * 1000));
    }
    
    private void validateJsonResponse(Response response) {
        //response.then().contentType(ContentType.JSON);
    }
}