package org.javiermf.features.models.tests;

/**
 * Test configuration constants
 * Generated by API Test Generator System
 */
public class TestConfig {
    
    public static final String BASE_URL = System.getProperty("api.base.url", "http://localhost:8080");
    public static final int DEFAULT_TIMEOUT = 30;
    public static final String API_VERSION = "1.0.0";
    
    // Test data constants
    public static final String TEST_USER_EMAIL = "test@example.com";
    public static final String TEST_USER_NAME = "Test User";
    public static final int TEST_USER_ID = 1;
    
    // Response validation constants
    public static final String JSON_CONTENT_TYPE = "application/json";
    public static final String XML_CONTENT_TYPE = "application/xml";
    
    private TestConfig() {
        // Utility class
    }
}